import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>ky-blog</title>
        <meta name="description" content="ky-blog Generated by Kim Yoo" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <h1 className="text-3xl font-bold underline">main</h1>
      </div>
    </>
  );
}
